server:
  port: 80

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/,http://localhost:8081/eureka/


spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # \u662F\u5426\u5F00\u542F\u57FA\u4E8E\u670D\u52A1\u53D1\u73B0\u7684\u8DEF\u7531\u89C4\u5219
          lower-case-service-id: true # \u662F\u5426\u5C06\u670D\u52A1\u540D\u79F0\u8F6C\u5C0F\u5199
        #routes:
      # - id: product-service
          # uri: lb://http://localhost:9090/
        #   uri: lb://service-provider
       #   predicates:
       #     - Path=/product/**
       # - id: order-service
       #   uri: lb://service-consumer
       #   predicates:
       #     - Path=/order/**