server:
  port: 9090

spring:
  application:
    name: product-service

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/,http://localhost:8081/eureka/
